version: '3.3'
services:
  front:
    build: 
      context: ..
      dockerfile: Dockerfile.dev
    volumes:
      - ..:/workspace:cached
      - /workspace/node_modules
    command: /bin/sh -c "npm run build;npm start;while sleep 1000; do :; done" 
    container_name: frontend_server
    ports:
     - "3000"
  reverse-proxy:
    image: nginx:latest
    volumes:
      - ../nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "42962:80"
    depends_on:
      - front
      - api
  api:
    image: harunari/financial_analysis_api:stable
    container_name: analysis_api
    environment:
      DB_SERVERNAME: report_rdb_primary
      DB_USERID: postgres
      DB_NAME: postgres
      DB_PORT: 5432
      DB_PASSWORD: mysecretpassword
      ASPNETCORE_URLS: http://+:80
      ASPNETCORE_ENVIRONMENT: Development
    ports:
     - "80"
    depends_on:
      - rdb_primary
      - aquire_financial_reports_batch
  rdb_primary:
    image: harunari/financial_report_primary_database:stable
    container_name: report_rdb_primary
    volumes:
      - primary_database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: mysecretpassword
    expose:
      - 5432
  import_corporation_info_batch:
    image: harunari/import_corporation_info_batch:stable
    environment:
      DB_SERVERNAME: report_rdb_primary
      DB_USERID: postgres
      DB_NAME: postgres
      DB_PORT: 5432
      DB_PASSWORD: mysecretpassword
    depends_on:
      - rdb_primary
  aquire_financial_reports_batch:
    image: harunari/aquire_financial_reports_batch:stable
    container_name: aquire_financial_reports_batch
    entrypoint: > 
      /bin/bash -c "
        # これがないとcron jobで環境変数を読み込めない
        printenv | grep -v "no_proxy" >> /etc/environment;mkdir /etc/cron.d;
        # 毎日午前1時にバッチ実行
        echo '0 1 * * * dotnet /app/AquireFinancialReports.dll >> /var/log/cron.log 2>&1' >> /etc/cron.d/batch-cron;
        chmod 0644 /etc/cron.d/batch-cron;
        apt update && apt install -y cron;
        service cron start;
        crontab /etc/cron.d/batch-cron;
        while sleep 1000; do :; done"
    environment:
      DB_SERVERNAME: report_rdb_primary
      DB_USERID: postgres
      DB_NAME: postgres
      DB_PORT: 5432
      DB_PASSWORD: mysecretpassword
    depends_on:
      - rdb_primary
      - aquire_account_items_batch
      - import_corporation_info_batch
  aquire_account_items_batch:
    image: harunari/aquire_account_items_batch:stable
    environment:
      DB_SERVERNAME: report_rdb_primary
      DB_USERID: postgres
      DB_NAME: postgres
      DB_PORT: 5432
      DB_PASSWORD: mysecretpassword
    depends_on:
      - rdb_primary
volumes:
  primary_database:
    driver: local

