# Node.js with webpack
# Build a Node.js project using the webpack CLI.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master
- release/*
- develop
- feature/*

pool:
  vmImage: 'ubuntu-20.04'

steps:
- template: buildAndTest.yml

- ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/master') }}:
  - template: pushImages.yml
    parameters:
      imageTag: 'stable'

- ${{ if startsWith(variables['Build.SourceBranch'], 'refs/heads/release/') }}:
  - template: pushImages.yml
    parameters:
      imageTag: 'beta'

- ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/develop') }}:
  - template: pushImages.yml
    parameters:
      imageTag: 'alpha'
